baseURL = 'https://dragomirt.com/'
languageCode = 'en-us'
title = 'Dragomir Țurcanu'
theme = 'mini'

defaultContentLanguage = "en"


[ params ]

  author = "dragomirt"
  bio = "Software engineer and tech enthusiast"
  description = "Software engineer and tech enthusiast"
  enableRSS = false
  enableComments = true
#   enableGoogleAnalytics: true
    showPowerBy = false
    showToc = true

    customCSS = [
        "css/custom.css"
        ]


[ social ]
  # e.g.
  github = "https://github.com/dragomirt"
  twitter = "https://twitter.com/dragomirturcanu"
#   stackoverflow: your-github-link
  # facebook: your-facebook-link

[ markup ]
    [ highlight ]
        guessSyntax = true