baseURL = 'https://dragomirt.com/'
languageCode = 'en-us'
title = 'Dragomir Țurcanu'
theme = 'mini'

defaultContentLanguage = "en"
googleAnalytics = "G-RZ8GW0WK4L"


[ params ]

  author = "dragomirt"
  bio = "Software engineer and tech enthusiast"
  description = "Software engineer and tech enthusiast"
  enableRSS = false
  enableComments = true
  enableGoogleAnalytics = true
    showPowerBy = false
    showToc = true

    customCSS = [
        "css/custom.css"
        ]


[ social ]
  # e.g.
  gmail = "mailto:dtu@dragoimrt.com"
  github = "https://github.com/dragomirt"
  twitter = "https://twitter.com/dragomirturcanu"
  linkedin = "https://www.linkedin.com/in/dragomirt/"
#   stackoverflow: your-github-link
  # facebook: your-facebook-link

[ markup ]
    [ highlight ]
        guessSyntax = true